import openai
import torch
from diffusers import StableDiffusionPipeline
from PIL import Image
from IPython.display import display
from models import get_story_prompt, generate_text, clean_text, load_model, generate_images_from_prompts, display_text_and_images, save_images, image_grid
from tokens import openai_token, hugging_token

# Generating the story using the above defined Functions
prompt = get_story_prompt()
response = generate_text(prompt, openai_token)
text_list = clean_text(response)
print(text_list)


# Loading the Image Generation Model
model_id = "dreamlike-art/dreamlike-photoreal-2.0"
device = "cuda"
pipe = load_model(model_id, hugging_token, device,
                  torch_dtype=torch.float16)
# Generating Images from the paragraph prompts generated by story generator model.
num_imgs = 1
seed = 1024
num_inference_steps = 50
guidance_scale = 8
images = generate_images_from_prompts(
    pipe, text_list, num_imgs, seed, num_inference_steps, guidance_scale)
# To Display Generated Images and Text
display_text_and_images(images, text_list)
# To save Generated Images
save_images(images)
# To save Images Inside a Grid
grid = image_grid(images, rows=3, cols=3)
display(grid)
grid.save(f'grid.png')
