import openai
import torch
from diffusers import StableDiffusionPipeline
from PIL import Image
from IPython.display import display
import story_generator as sg
import image_generator as ig
from openai_token import openai_token
from huggingface_token import hugging_token

# Generating the story using the above defined Functions
prompt = sg.get_story_prompt()
response = sg.generate_text(prompt, openai_token)
text_list = sg.clean_text(response)
print(text_list)


# Loading the Image Generation Model
model_id = "dreamlike-art/dreamlike-photoreal-2.0"
device = "cuda"
pipe = ig.load_model(model_id, hugging_token, device,
                     torch_dtype=torch.float16)
# Generating Images from the paragraph prompts generated by story generator model.
num_imgs = 1
seed = 1024
num_inference_steps = 50
guidance_scale = 8
images = ig.generate_images_from_prompts(
    pipe, text_list, num_imgs, seed, num_inference_steps, guidance_scale)
# To Display Generated Images and Text
ig.display_text_and_images(images, text_list)
# To save Generated Images
ig.save_images(images)
# To save Images Inside a Grid
grid = ig.image_grid(images, rows=3, cols=3)
display(grid)
grid.save(f'grid.png')
